config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "works#index"

  resources :works do
    resources :reviews do

    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :url, ImageUploader
  belongs_to :work, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  has_many :reviews
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

  end

  def new 
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to work_path(params[:work_id])
    else   
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:comment).merge(work_id: params[:work_id])
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def new
    @work = Work.new
    @work.images.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to root_path
    else   
      render :new
    end
  end

  def show
    @work = Work.find(params[:id])
    # @reviews = Review.where(work_id: params[:id])
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, images_attributes: [:url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movie
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/reviews/new.html.haml
%main.reviews-new
  reviews#new
  = form_for @review, url:{controller: :reviews, action: :create}, method: :post do |f|
    = f.text_area :comment
    = f.submit '送信ボタン'

app/views/works/index.html.haml
%main.works-index
  works#index
  .recent
    -# - if @works.persisted?
    - @works.each do |work|
      = link_to work_path(work.id) do
        = work.id
        = work.title
        %br
    = link_to '新規作品投稿', new_work_path

app/views/works/new.html.haml
%main.works-new
  works#new
  = form_for @work do |f|
    = f.text_field :title
    = f.number_field :year
    = f.fields_for :images do |image|
      = image.file_field :url
      
    %br
    = f.submit '送信ボタン'

app/views/works/show.html.haml
%main.work-show
  id:
  = @work.id
  %br/
  title:
  = @work.title 
  %br/
  year:
  = @work.year
  %br
  = link_to "感想投稿", new_work_review_path(params[:id])
  %br

  - if @work.images.blank?
    画像はありません
    %br/
  - else
    = image_tag @work.images[0].url.url
    %br/
  - if @work.reviews.blank?
    感想がありません
  - else
    - @work.reviews.each_with_index do |review, i|
      #{i} comment:
      = review.comment
      %br